before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/airport-json/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
brews:
  - description: JSONize airport -I of macOS
    tap:
      owner: pen
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
